### ISSUE TITLE
Idea: iPXE

### ISSUE THREAD

**Issue by jacaudi** [jeefy/booty#6]
Would you be opposed to adding iPXE to allow the file transfer to go over http(s) instead of tftp?

**Comment by jeefy** [comment]
Not opposed, but... 

iPXE doesn't work for everyone (myself included) due to the bootlooping issue iPXE has. And while there are workarounds, I opted for the "simplest" route since I don't care how long a node takes to reboot/rejoin. 

I think there's probably a way to tackle this so it's an option for those who want to use iPXE. :) So I'm +1

**Comment by jeefy** [comment]
Done and confirmed on my homelab! 

Currently works off ghcr.io/jeefy/booty:main but will be in the next release once I finish the other idea I'm knocking out. :) 

Was fun seeing a node boot in about thirty seconds instead of like ten minutes.
